tcpのexecを作った
arkedge/kble pull request #98
Opened 2024-05-27 07:24 UTC by shunsuke-shimomura

#93 でのレビューを受けて、execでtcpの受け口を作ることにした。
とりあえず作ったけど動かないので皆さん助けてください！！

2024-05-27 07:50 UTC, kobkaz commented
手元で簡単に試してみましたが、ひとまず正常に動いていると思いますよ

2024-05-27 07:51 UTC, shunsuke-shimomura commented
そうすると自分が試してるTCP通信側の問題ということでしょうか

2024-05-27 08:08 UTC, shunsuke-shimomura commented
手元にあったTCPポートが複数接続を禁止してるだけだったので、適当なTCPポートを作ったらうまく動きました！

2024-05-27 08:29 UTC, shunsuke-shimomura commented
マージしてもいいですか？

2024-05-27 08:31 UTC, KOBA789 requested changes

2024-05-27 08:31 UTC, KOBA789 commented on kble-tcp/src/main.rs
> +    let addr = format!("{}:{}", args.get(1).unwrap(), args.get(2).unwrap());
コマンドライン引数の取り扱いは clap を用いて欲しい

2024-05-27 08:32 UTC, kobkaz commented
すみません　まだレビューできてないので
あとどこにもはっきり書かれてはいないのですが、マージボタンを押す係は @KOBA789　がやる方針になっています

2024-05-27 08:33 UTC, KOBA789 requested changes

2024-05-27 08:33 UTC, KOBA789 commented on kble-tcp/Cargo.toml
> +notalawyer-clap.workspace = true
末尾に改行文字が欲しい

2024-05-27 08:33 UTC, KOBA789 commented on kble-tcp/Cargo.toml
> +eb90 = "0.1.1"
eb90 は不要では？

2024-05-27 08:33 UTC, KOBA789 commented on kble-tcp/Cargo.toml
> +tracing-subscriber.workspace = true
tracing も活用できてなさそう。deps に含めるなら eprintln ではなく tracing をちゃんと使うべき

2024-05-27 08:46 UTC, shunsuke-shimomura commented
ありがとうございます！修正します

2024-05-27 09:32 UTC, KOBA789 requested changes

2024-05-28 04:40 UTC, KOBA789 reviewed
コードを読む限りでは大丈夫そう。
動作確認はできていないので、もしどなたか余裕あれば代わりにお願いしたいです（キツそうなら私の方でやります）

2024-05-28 04:42 UTC, KOBA789 commented
@shunsuke-shimomura （どこにも書いてないんですが）一応コミットメッセージは英語で統一しているので、rebase とかで書き直してもらっていいですか？　書き直したら force push しちゃってよいです。

2024-05-28 04:42 UTC, KOBA789 commented
@shunsuke-shimomura （どこにも書いてないんですが）一応コミットメッセージは英語で統一しているので、rebase とかで書き直してもらっていいですか？　書き直したら force push しちゃってよいです。

2024-05-28 04:57 UTC, kobkaz commented
動作確認については

```
{
  {
  plugs: {
    tcp : "exec:kble-tcp 127.0.0.1 8000"
  },
  links : {
    tcp: "tcp"
  }
}
```
を用いて、127.0.0.1:8000でlistenしているサーバからクライアントに向けて送信したデータがサーバに返ってくることを確認しています

2024-05-28 04:58 UTC, KOBA789 approved these changes
@shunsuke-shimomura コミットメッセージ直してもらったらマージします

2024-05-29 04:55 UTC, merged